on: [push]

name: ARMv7 build

jobs:
  linux_arm7:
    name: Linux ARMv7
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install toolchain if not cross-compiling
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: armv7-unknown-linux-gnueabihf
      - name: Install cross
        shell: bash
        run: |
          cargo install cross
      - name: check
        shell: bash
        run: |
          ls
      - name: Build
        shell: bash
        run: |
          cargo build --target armv7-unknown-linux-gnueabihf