on: [push]
# docker run -v ./:/project:rw hb build --release -v --target armv7-unknown-linux-gnueabihf
name: ARMv7 build

jobs:
  build_pi:
    name: Linux ARMv7
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup docker build
        uses: docker/setup-buildx-action@v2
      - name: Docker build image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: "Dockerfile"
          tags: marisusis/pi-build:latest
          load: true
          cache-from: type=registry,ref=user/app:latest
          cache-to: type=inline
          push: false
      - name: Docker run
        shell: bash
        run: |
          docker run -v ./:/project:rw marisusis/pi-build:latest build --release --target armv7-unknown-linux-gnueabihf
      - name: Store the binary
        uses: actions/upload-artifact@v3
        with:
          name: arm-build
          path: ./target/armv7-unknown-linux-gnueabihf/release/heartbeat-acquisition
  publish-release:
    needs: build_pi
      name: Publish Github Release
      runs-on: ubuntu-latest
      steps:
        - name: Download the binary
          uses: actions/download-artifact@v3
          with:
            name: arm-build
            path: ./
        - name: Build archive
          shell: bash
          run: |
            tar -czf heartbeat-acquisition-rpi.tar.gz heartbeat-acquisition
        - name: Release
          uses: softprops/action-gh-release@v1
          with:
          files: |
            ./heartbeat-acquisition-rpi.tar.gz

        